version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"
